### ISSUE TITLE
When turning on the speaker, the microphone doesn't work

### ISSUE THREAD

**Issue by ydan87** [plivo/plivo-ios-sdk2-examples#2]
Hello there,
I've noticed an issue in the app, in which when I turn the speaker on, the other side won't hear me. Maybe the microphone got off when the speaker got on, for some reason...

What can be the cause for that?

**Comment by SivaPlivo** [comment]
Thank you for reaching out to us and showing your interest in Plivo iOS SDK. 

We just found out that... It is Toggle issue. When we press the Speaker button it is actually muting the call, that is why remote side won't hear you. 

We are fixing it.

**Comment by SivaPlivo** [comment]
@ydan87  Meanwhile, you can use the (Mute/Speaker) button in opposite way to turn on the speaker and mute the call.
