### ISSUE TITLE
Does not compile/ run 

### ISSUE THREAD

**Issue by codeinpeace** [plivo/plivo-ios-sdk2-examples#37]
Hi,
I've just tried to run this sample. It fails to run in both the simulator and a real device. 

I can see recent code changes in the repo but has anyone actually tried to run it recently? 
If something needs to be done to make it run correctly, perhaps the documentation is out of date - I have followed existing instructions and it still fails to run.

Any help from the Plivo team will be appreciated.

**Comment by pothinenikarthik-plivo** [comment]
Hi,
Can you help us with the error you are getting?

**Comment by codeinpeace** [comment]
Before we get to it, I am curious to know if you have actually tried to compile it yourself? I am curious to know if if you have been able to compile and run it successfully in a simulator and a device.

Have you tied to follow step 1 of your own instruction to see if it works?

**Comment by pothinenikarthik-plivo** [comment]
We updated our SDK reference link(https://www.plivo.com/docs/sdk/client/ios/reference). We ran our sample app according to steps provided and everything works fine. If you face any issue, Please raise the issue with support@plivo.com
