### ISSUE TITLE
Application crashes 

### ISSUE THREAD

**Issue by codeinpeace** [plivo/plivo-ios-sdk2-examples#38]
Hi,
I have just checked out the latest code from here. It crashed with the following error message:
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'
*** First throw call stack:

Please see screenshot below. I am very curious to see this SDK work just once. I am told this works. Perhaps you can help me to get this going?

<img width="1184" alt="Screen Shot 2019-09-22 at 4 46 33 pm" src="https://user-images.githubusercontent.com/657516/65383421-bda3cd00-dd58-11e9-84c8-29c4c7f27756.png">

**Comment by eniyavan-muruganantham-plivo** [comment]
@codeinpeace Please raise a ticket to support@plivo.com
