### ISSUE TITLE
Endpoint delegate methods not being called

### ISSUE THREAD

**Issue by mattfox12** [plivo/plivo-ios-sdk2-examples#5]
I'm trying to run this example targeting iOS 10, I'm finding it does not trigger the endpoint delegate methods. Specifically the onLogin (or onLoginFailed), which prevents the application from moving past the Login screen.

**Comment by eniyavan-muruganantham-plivo** [comment]
@mattfox12 Requesting to use our latest example application.
If the issue still persists please write to support@plivo.com.
