### ISSUE TITLE
Building plivo-ios-sdk2-examples using m2 MacBook fails to link PlivoVoiceKit.framework

### ISSUE THREAD

**Issue by nangchan** [plivo/plivo-ios-sdk2-examples#51]
Building plivo-ios-sdk2-examples using m1/m2 MacBook fails with `clang: error: linker command failed with exit code 1`.
Building using intel MacBook 2019 works fine.

**Details**
Xcode 15.0.1
MacBook Pro 16-in 2023 (m2 chip)
macOS Sonoma 14.1.2

**Xcode Output**
Ld /$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator/SwiftVoiceCallingApp.app/SwiftVoiceCallingApp normal (in target 'SwiftVoiceCallingApp' from project 'SwiftVoiceCallingApp')
    cd /$HOME/plivo-ios-sdk2-examples/SwiftVoiceCallingApp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -O0 -L$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -L$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/lib/swift -F$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -F$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator -F$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator/APAddressBook -F$HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator/ReachabilitySwift -F$HOME/plivo-ios-sdk2-examples/SwiftVoiceCallingApp/SwiftVoiceCallingApp -filelist $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/Objects-normal/arm64/SwiftVoiceCallingApp.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker $HOMEhan/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/Objects-normal/arm64/SwiftVoiceCallingApp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/Objects-normal/arm64/SwiftVoiceCallingApp.swiftmodule -framework APAddressBook -framework AddressBook -framework ReachabilitySwift -framework SystemConfiguration -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/SwiftVoiceCallingApp.app-Simulated.xcent -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __ents_der -Xlinker $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/SwiftVoiceCallingApp.app-Simulated.xcent.der -framework UserNotifications -framework UserNotificationsUI -framework SystemConfiguration -framework Security -framework PushKit -framework Intents -framework QuartzCore -framework OpenGLES -framework UIKit -framework CFNetwork -framework AudioToolbox -framework AVFoundation -framework Foundation -framework CoreData -framework CoreGraphics -framework CoreMedia -framework CallKit -framework SafariServices -framework PlivoVoiceKit -framework Pods_SwiftVoiceCallingApp -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Intermediates.noindex/SwiftVoiceCallingApp.build/Debug-iphonesimulator/SwiftVoiceCallingApp.build/Objects-normal/arm64/SwiftVoiceCallingApp_dependency_info.dat -o $HOME/Library/Developer/Xcode/DerivedData/SwiftVoiceCallingApp-gpgxaqghwalmqudmztfhnejtsiuy/Build/Products/Debug-iphonesimulator/SwiftVoiceCallingApp.app/SwiftVoiceCallingApp

ld: building for 'iOS-simulator', but linking in dylib ($HOME/plivo-ios-sdk2-examples/SwiftVoiceCallingApp/SwiftVoiceCallingApp/PlivoVoiceKit.framework/PlivoVoiceKit) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sanyamjain-plivo** [comment]
PlivoVoiceKit SDK is primarily designed for iOS architecture and performs seamlessly on actual iPhone devices.
